package com.kalyansky.pdf.example;

import com.kalyansky.pdf.PdfGenerator;
import com.kalyansky.pdf.model.PdfContent;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates a sample PDF. Run with {@code mvn compile exec:java}, optionally passing
 * the output path: {@code mvn compile exec:java -Dexec.args="out/report.pdf"}.
 */
public final class ExampleDocument {

    private ExampleDocument() {
    }

    public static void main(String[] args) throws IOException {
        Path target = Path.of(args.length > 0 ? args[0] : "output/example.pdf");

        PdfContent content = PdfContent.builder("Monthly Sales Report")
                .author("Kalyan")
                .subject("Sales summary generated with iText")
                .keywords("sales, report, itext")
                .heading("Summary")
                .paragraph("This report was generated by the iText PDF generator. "
                        + "It shows headings, paragraphs, lists and tables.")
                .bulletList(List.of(
                        "Revenue grew 12% compared to last month",
                        "Three new customers signed up",
                        "Average order value: $245"))
                .heading("Orders", 2)
                .table(
                        List.of("Order #", "Customer", "Items", "Total"),
                        List.of(
                                List.of("1001", "Acme Corp", "3", "$540.00"),
                                List.of("1002", "Globex", "1", "$120.00"),
                                List.of("1003", "Initech", "5", "$980.00")),
                        List.of(1f, 3f, 1f, 1.5f))
                .heading("Notes", 2)
                .paragraph("Figures are provisional until the month is closed.")
                .build();

        new PdfGenerator().generate(content, target);
        System.out.println("PDF written to " + target.toAbsolutePath());
    }
}
